data_dir: D:\FAKI\NEWMLMODL\dataset\windows_evtx_bos_lowunk
dataset_name: windows_apt
log_file: windows_evtx_bos_lowunk.log
embeddings: embeddings_average.json

grouping: sliding
session_level: entry
window_size: 30
step_size: 1
is_chronological: true
split_mode: per_host_chronological

sequential: true
semantic: false
quantitative: false

model_name: DeepLog
embedding_dim: 300
dropout: 0.1
hidden_size: 128
num_layers: 2
history_size: 20
topk: 5

optimizer: adam
adam_beta1: 0.9
adam_beta2: 0.999
lr: 0.001
max_epoch: 6

output_dir: D:\FAKI\NEWMLMODL\output_windows_evtx_bos_lowunk
resume: false
train_size: 0.8
valid_ratio: 0.1
batch_size: 128
accumulation_step: 1
scheduler: linear
warmup_rate: 0.1
train: true
remove_duplicates: false
